export default {
  GET_MEMBERS_REQUEST: 'GET_MEMBERS_REQUEST',
  GET_MEMBERS_SUCCESS: 'GET_MEMBERS_SUCCESS',
  GET_MEMBERS_FAILURE: 'GET_MEMBERS_FAILURE',

  ADD_MEMBER_REQUEST: 'ADD_MEMBER_REQUEST',
  ADD_MEMBER_SUCCESS: 'ADD_MEMBER_SUCCESS',
  ADD_MEMBER_FAILURE: 'ADD_MEMBER_FAILURE',

  DELETE_MEMBER_REQUEST: 'DELETE_MEMBER_REQUEST',
  DELETE_MEMBER_SUCCESS: 'DELETE_MEMBER_SUCCESS',
  DELETE_MEMBER_FAILURE: 'DELETE_MEMBER_FAILURE',

  PATCH_MEMBER_REQUEST: 'PATCH_MEMBER_REQUEST',
  PATCH_MEMBER_SUCCESS: 'PATCH_MEMBER_SUCCESS',
  PATCH_MEMBER_FAILURE: 'PATCH_MEMBER_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  PATCH_USER_REQUEST: 'PATCH_USER_REQUEST',
  PATCH_USER_SUCCESS: 'PATCH_USER_SUCCESS',
  PATCH_USER_FAILURE: 'PATCH_USER_FAILURE',

  GET_TEAM_REQUEST: 'GET_TEAM_REQUEST',
  GET_TEAM_SUCCESS: 'GET_TEAM_SUCCESS',
  GET_TEAM_FAILURE: 'GET_TEAM_FAILURE',

  ADD_TEAM_REQUEST: 'ADD_TEAM_REQUEST',
  ADD_TEAM_SUCCESS: 'ADD_TEAM_SUCCESS',
  ADD_TEAM_FAILURE: 'ADD_TEAM_FAILURE',

  INIT_GAPI_REQUEST: 'INIT_GAPI_REQUEST',
  INIT_GAPI_SUCCESS: 'INIT_GAPI_SUCCESS',
  INIT_GAPI_FAILURE: 'INIT_GAPI_FAILURE',
  
  SET_MEMBER_FILTER: 'SET_MEMBER_FILTER',
  SET_MEMBER_SELECTED: 'SET_MEMBER_SELECTED',
  SET_IS_SIGNED_IN: 'SET_IS_SIGNED_IN',
};