export default {
  GET_MEMBERS_REQUEST: 'GET_MEMBERS_REQUEST',
  GET_MEMBERS_SUCCESS: 'GET_MEMBERS_SUCCESS',
  GET_MEMBERS_FAILURE: 'GET_MEMBERS_FAILURE',

  ADD_MEMBER_REQUEST: 'ADD_MEMBER_REQUEST',
  ADD_MEMBER_SUCCESS: 'ADD_MEMBER_SUCCESS',
  ADD_MEMBER_FAILURE: 'ADD_MEMBER_FAILURE',

  DELETE_MEMBER_REQUEST: 'DELETE_MEMBER_REQUEST',
  DELETE_MEMBER_SUCCESS: 'DELETE_MEMBER_SUCCESS',
  DELETE_MEMBER_FAILURE: 'DELETE_MEMBER_FAILURE',

  PATCH_MEMBER_REQUEST: 'PATCH_MEMBER_REQUEST',
  PATCH_MEMBER_SUCCESS: 'PATCH_MEMBER_SUCCESS',
  PATCH_MEMBER_FAILURE: 'PATCH_MEMBER_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  
  SET_MEMBER_FILTER: 'SET_MEMBER_FILTER'
};