export const actionTypes = {
  GET_MEMBERS_REQUEST: 'GET_MEMBERS_REQUEST',
  GET_MEMBERS_SUCCESS: 'GET_MEMBERS_SUCCESS',
  GET_MEMBERS_FAILURE: 'GET_MEMBERS_FAILURE',

  ADD_MEMBER_REQUEST: 'ADD_MEMBER_REQUEST',
  ADD_MEMBER_SUCCESS: 'ADD_MEMBER_SUCCESS',
  ADD_MEMBER_FAILURE: 'ADD_MEMBER_FAILURE',

  DELETE_MEMBER_REQUEST: 'DELETE_MEMBER_REQUEST',
  DELETE_MEMBER_SUCCESS: 'DELETE_MEMBER_SUCCESS',
  DELETE_MEMBER_FAILURE: 'DELETE_MEMBER_FAILURE',

  PATCH_MEMBER_REQUEST: 'PATCH_MEMBER_REQUEST',
  PATCH_MEMBER_SUCCESS: 'PATCH_MEMBER_SUCCESS',
  PATCH_MEMBER_FAILURE: 'PATCH_MEMBER_FAILURE',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  PATCH_USER_REQUEST: 'PATCH_USER_REQUEST',
  PATCH_USER_SUCCESS: 'PATCH_USER_SUCCESS',
  PATCH_USER_FAILURE: 'PATCH_USER_FAILURE',

  GET_TEAM_REQUEST: 'GET_TEAM_REQUEST',
  GET_TEAM_SUCCESS: 'GET_TEAM_SUCCESS',
  GET_TEAM_FAILURE: 'GET_TEAM_FAILURE',

  ADD_TEAM_REQUEST: 'ADD_TEAM_REQUEST',
  ADD_TEAM_SUCCESS: 'ADD_TEAM_SUCCESS',
  ADD_TEAM_FAILURE: 'ADD_TEAM_FAILURE',

  DELETE_TEAM_REQUEST: 'DELETE_TEAM_REQUEST',
  DELETE_TEAM_SUCCESS: 'DELETE_TEAM_SUCCESS',
  DELETE_TEAM_FAILURE: 'DELETE_TEAM_FAILURE',

  LEAVE_TEAM_REQUEST: 'LEAVE_TEAM_REQUEST',
  LEAVE_TEAM_SUCCESS: 'LEAVE_TEAM_SUCCESS',
  LEAVE_TEAM_FAILURE: 'LEAVE_TEAM_FAILURE',

  PATCH_TEAM_REQUEST: 'PATCH_TEAM_REQUEST',
  PATCH_TEAM_SUCCESS: 'PATCH_TEAM_SUCCESS',
  PATCH_TEAM_FAILURE: 'PATCH_TEAM_FAILURE',

  SEARCH_TEAM_REQUEST: 'SEARCH_TEAM_REQUEST',
  SEARCH_TEAM_SUCCESS: 'SEARCH_TEAM_SUCCESS',
  SEARCH_TEAM_FAILURE: 'SEARCH_TEAM_FAILURE',

  ADD_JOIN_TEAM_REQUEST_REQUEST: 'ADD_JOIN_TEAM_REQUEST_REQUEST',
  ADD_JOIN_TEAM_REQUEST_SUCCESS: 'ADD_JOIN_TEAM_REQUEST_SUCCESS',
  ADD_JOIN_TEAM_REQUEST_FAILURE: 'ADD_JOIN_TEAM_REQUEST_FAILURE',

  DELETE_JOIN_TEAM_REQUEST_REQUEST: 'DELETE_JOIN_TEAM_REQUEST_REQUEST',
  DELETE_JOIN_TEAM_REQUEST_SUCCESS: 'DELETE_JOIN_TEAM_REQUEST_SUCCESS',
  DELETE_JOIN_TEAM_REQUEST_FAILURE: 'DELETE_JOIN_TEAM_REQUEST_FAILURE',

  ADD_TEAM_MEMBER_REQUEST: 'ADD_TEAM_MEMBER_REQUEST',
  ADD_TEAM_MEMBER_SUCCESS: 'ADD_TEAM_MEMBER_SUCCESS',
  ADD_TEAM_MEMBER_FAILURE: 'ADD_TEAM_MEMBER_FAILURE',

  DELETE_TEAM_MEMBER_REQUEST: 'DELETE_TEAM_MEMBER_REQUEST',
  DELETE_TEAM_MEMBER_SUCCESS: 'DELETE_TEAM_MEMBER_SUCCESS',
  DELETE_TEAM_MEMBER_FAILURE: 'DELETE_TEAM_MEMBER_FAILURE',

  TRY_LOGIN_REQUEST: 'TRY_LOGIN_REQUEST',
  TRY_LOGIN_SUCCESS: 'TRY_LOGIN_SUCCESS',
  TRY_LOGIN_FAILURE: 'TRY_LOGIN_FAILURE',

  INIT_GOOGLESIGNIN_REQUEST: 'INIT_GOOGLESIGNIN_REQUEST',
  INIT_GOOGLESIGNIN_SUCCESS: 'INIT_GOOGLESIGNIN_SUCCESS',
  INIT_GOOGLESIGNIN_FAILURE: 'INIT_GOOGLESIGNIN_FAILURE',
  
  SET_IS_DARK_MODE: 'SET_IS_DARK_MODE',
  SET_IS_SIGNED_IN: 'SET_IS_SIGNED_IN',
  SET_INITIALIZED: 'SET_INITIALIZED',
  SET_SEARCH_TEAM_RESULT: 'SET_SEARCH_TEAM_RESULT',

  SET_ALERT: 'SET_ALERT'
};

export const routeNameMap = {
  '/home': 'Home',
  '/team': '戰隊管理',
  '/team/member': '成員管理',
  '/team/permission': '權限管理',
};